package personal;
//Task is:
//        Using OOP, create a Class Account, which has fields Login*, Password*, Firstname*, Lastname*, Age*, City, Place of work, Marital status, ID.
//        Fields marked with star * are mandatory
//        Create several constructors (for all mandatory and each non-mandatory fields)
//        ID has to be generated by program and assigned to each new account
//        Implement Encapsulation with restrictions (like age cannot be negative number and etc)
//        In new Class, create three users
//        For user1 - change firstname
//        For user2 - change City
//        For user3 - change both login and password
//        Printout fields before and after the change of each user

import java.sql.SQLOutput;
import java.util.Scanner;

public class Account {
    private String login, password;
    String firstName, lastName;
    private int age;
    String city, workPlace, maritalStatus;
    private String id;

    public Account() {
    }
    //public Account(String fName){
    //    this.firstName = fName;
    // }

    public Account(String cLogin, String cPassword) {
        this.login = cLogin;
        this.password = cPassword;
    }

    public Account(String cFirstName, String cLastName, int cAge, String cMaritalStatus) {
        this.firstName = cFirstName;
        this.lastName = cLastName;
        this.age = cAge;
        this.maritalStatus = cMaritalStatus;

    }

    public void setAge(int age) {

        this.age = age;
    }

    public int getAge() {
        return age;
    }

    public void setId(String id) {

        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getLogin() {
        return login;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return password;
    }

    public void createID() {
        /*Algorithm for creating unique id:
        id = concatenation of "first 2 chars of last name" + "2 digits of age" + "Marital status" + "last 2 chars of 1st name"
        Marital status can be M(married), S(single), D(divorced), O(if no marital status provided by user)
         */

        id = this.lastName.toUpperCase().substring(0, 2) + this.age + this.maritalStatus + this.firstName.toUpperCase().substring(this.firstName.length() - 2);
        setId(id);
    }

    public void printIDResults(int i) {
        System.out.println("User" + (i + 1) + ": " + this.id);
    }

    public String changeFirstName() {

        String oldFirstName = this.firstName;
        System.out.println("\nDear " + oldFirstName + ", " + "enter your new first name:");
        Scanner sc = new Scanner(System.in);
        this.firstName = sc.nextLine();
        return oldFirstName;
    }
    public String changeCity() {

        String oldCity = this.city;
        System.out.println("\nDear " + this.firstName + ", " + "enter your new city name:");
        Scanner sc = new Scanner(System.in);
        this.city = sc.nextLine();
        return oldCity;
    }
    public void changeLogin(String oldLogin, String oldPassword) {

        //String oldCity = this.city;
        System.out.println("\nDear " + this.firstName + ", " + "enter your new loginId:");
        Scanner sc = new Scanner(System.in);
        this.login = sc.nextLine();
        System.out.println("Now enter your new password:");
        this.password = sc.nextLine();

    }

}



class Users {
    public static void main(String[] args) {

        Account[] user = new Account[3];
        user[0] = new Account("Laila", "Jahan", 29, "S");
        user[1] = new Account("Ram", "Krishna", 35, "M");
        user[2] = new Account("Holly", "Davis", 60, "O");

        System.out.println("*** Printing user IDs *****");
        for (int i = 0; i < user.length; i++) {
            user[i].createID();
            user[i].printIDResults(i);
        }
        System.out.println("***************************");

        System.out.println("Your 1st name changed from " + user[0].changeFirstName() + " to " + user[0].firstName+".");

        System.out.println("Your city name changed from " + user[1].changeCity() + " to " + user[1].city+".");


        user[2].changeLogin("Holly1", "daviS#123");

        System.out.println("Your new loginID is: "+user[2].getLogin()+ " and password is: "+user[2].getPassword());

    }
}





